name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install Dependencies
      run: |
        cd functions
        npm ci
        
    - name: Run Linter
      run: |
        cd functions
        npm run lint
        
    - name: Build
      run: |
        cd functions
        npm run build
        
    # Uncomment when tests are added
    # - name: Run Tests
    #   run: |
    #     cd functions
    #     npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        
    - name: Install Firebase CLI
      run: npm install -g firebase-tools
      
    - name: Deploy to Firebase
      run: |
        cd functions
        npm ci
        npm run deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }} 